manifest:
  remotes:
    - name: avengineers
      url-base: https://github.com/avengineers

  projects:
    - name: spl
      path: modules/spl
      remote: avengineers
      revision: e3007ac2667c21e9eb3ee61662ceb4a7a3f136c7
    - name: spl-extension-example
      path: modules/spl-extension-example
      remote: avengineers
      revision: d74e6b64fd8967238be84570863d7522b80337d4