name: selftests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true 
      - name: install tools and run selftests
        run: |
          .\test.ps1
        shell: powershell
      - uses: actions/upload-artifact@v2
        with:
          name: quality-gate-results.zip
          retention-days: 90
          path: test/output/test-report.xml
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: unittest-results.zip
          retention-days: 90
          path: "build/**/junit.xml"
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage.zip
          retention-days: 90
          path: build/**/coverage/*
          if-no-files-found: error
